// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableButtonController from "./disable_button_controller"
application.register("disable-button", DisableButtonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchMatchesController from "./search_matches_controller"
application.register("search-matches", SearchMatchesController)

import LocationSearchController from "./location_search_controller"
application.register("location-search", LocationSearchController)