meta_product_name: "FanFind"
meta_title: "FanFind - Find your place off the stands"
meta_description: "Team up to watch the FIFA World Cup. Find events near you or create your own,
                    chat with other fans, and share posts."
meta_image: "metatag-photo.png"
